=== fdelcastillo/Freebase/schemas/search-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "result" : {
      "type" : "array" ,
      "required" : false ,
      "items" : [
        {
          "type" : "object" ,
          "properties" : {
            "mid" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "notable" : {
              "type" : "object" ,
              "required" : false ,
              "properties" : {
                "name" : {
                  "type" : "string" ,
                  "required" : false
                } ,
                "id" : {
                  "type" : "string" ,
                  "required" : false
                }
              }
            } ,
            "lang" : {
              "type" : "string" ,
              "required" : false
            } ,
            "score" : {
              "type" : "number" ,
              "required" : false
            }
          }
        } , {
          "type" : "object" ,
          "properties" : {
            "mid" : {
              "type" : "string" ,
              "required" : false
            } ,
            "id" : {
              "type" : "string" ,
              "required" : false
            } ,
            "name" : {
              "type" : "string" ,
              "required" : false
            } ,
            "lang" : {
              "type" : "string" ,
              "required" : false
            } ,
            "score" : {
              "type" : "number" ,
              "required" : false
            }
          }
        }
      ]
    } ,
    "cursor" : {
      "type" : "number" ,
      "required" : false
    } ,
    "cost" : {
      "type" : "number" ,
      "required" : false
    } ,
    "hits" : {
      "type" : "number" ,
      "required" : false
    }
  }
}

=== fdelcastillo/Freebase/examples/search-example.json
{
  "status" : "200 OK" ,
  "result" : [
    {
      "mid" : "/m/0bkf4" ,
      "id" : "/en/bob_marley" ,
      "name" : "Bob Marley" ,
      "notable" : {
        "name" : "Musical Artist" ,
        "id" : "/music/artist"
      } ,
      "lang" : "en" ,
      "score" : 78.634216
    } , {
      "mid" : "/m/01vrncs" ,
      "id" : "/en/bob_dylan" ,
      "name" : "Bob Dylan" ,
      "notable" : {
        "name" : "Folk rock Artist" ,
        "id" : "/m/016jny"
      } ,
      "lang" : "en" ,
      "score" : 75.307129
    } , {
      "mid" : "/m/015cbq" ,
      "id" : "/en/bob_hope" ,
      "name" : "Bob Hope" ,
      "notable" : {
        "name" : "Comedian" ,
        "id" : "/m/018gz8"
      } ,
      "lang" : "en" ,
      "score" : 60.908581
    } , {
      "mid" : "/m/01pbxb" ,
      "id" : "/en/bob_seger" ,
      "name" : "Bob Seger" ,
      "notable" : {
        "name" : "Heartland rock Artist" ,
        "id" : "/m/05hs4r"
      } ,
      "lang" : "en" ,
      "score" : 55.450382
    } , {
      "mid" : "/m/09wz9" ,
      "id" : "/en/bobsleigh" ,
      "name" : "Bobsleigh" ,
      "notable" : {
        "name" : "Sport" ,
        "id" : "/sports/sport"
      } ,
      "lang" : "en" ,
      "score" : 53.285572
    } , {
      "mid" : "/m/02fj27" ,
      "id" : "/en/bob_cut" ,
      "name" : "Bob cut" ,
      "lang" : "en" ,
      "score" : 51.77486
    } , {
      "mid" : "/m/0fhkx" ,
      "id" : "/en/bob_dole" ,
      "name" : "Bob Dole" ,
      "notable" : {
        "name" : "U.S. Congressperson" ,
        "id" : "/government/u_s_congressperson"
      } ,
      "lang" : "en" ,
      "score" : 49.349247
    } , {
      "mid" : "/m/01z_dc" ,
      "id" : "/en/bob_the_builder" ,
      "name" : "Bob the Builder" ,
      "notable" : {
        "name" : "Children's TV Program" ,
        "id" : "/m/0pr6f"
      } ,
      "lang" : "en" ,
      "score" : 48.611294
    } , {
      "mid" : "/m/0fl08s" ,
      "id" : "/en/the_bob_tom_show" ,
      "name" : "The Bob & Tom Show" ,
      "notable" : {
        "name" : "Broadcast Content" ,
        "id" : "/broadcast/content"
      } ,
      "lang" : "en" ,
      "score" : 45.752556
    } , {
      "mid" : "/m/03xhfk" ,
      "id" : "/en/bob_holly" ,
      "name" : "Hardcore Holly" ,
      "notable" : {
        "name" : "Wrestler" ,
        "id" : "/m/02nx2gc"
      } ,
      "lang" : "en" ,
      "score" : 40.662376
    } , {
      "mid" : "/m/01kk3lb" ,
      "id" : "/en/bob_wills" ,
      "name" : "Bob Wills" ,
      "notable" : {
        "name" : "Western swing Artist" ,
        "id" : "/m/02wydx"
      } ,
      "lang" : "en" ,
      "score" : 38.773483
    } , {
      "mid" : "/m/01l87db" ,
      "id" : "/en/bob_geldof" ,
      "name" : "Bob Geldof" ,
      "notable" : {
        "name" : "Rock Artist" ,
        "id" : "/m/06by7"
      } ,
      "lang" : "en" ,
      "score" : 37.039284
    } , {
      "mid" : "/m/02ht0ln" ,
      "id" : "/en/bob_marley_the_wailers" ,
      "name" : "Bob Marley & The Wailers" ,
      "notable" : {
        "name" : "Ska Artist" ,
        "id" : "/m/06rqw"
      } ,
      "lang" : "en" ,
      "score" : 35.457142
    } , {
      "mid" : "/m/05kkq7" ,
      "id" : "/en/bob_orton_jr" ,
      "name" : "Bob Orton, Jr." ,
      "notable" : {
        "name" : "Wrestler" ,
        "id" : "/m/02nx2gc"
      } ,
      "lang" : "en" ,
      "score" : 35.056168
    } , {
      "mid" : "/m/071hsq" ,
      "id" : "/en/bob_sinclar" ,
      "name" : "Bob Sinclar" ,
      "notable" : {
        "name" : "Remixer" ,
        "id" : "/m/05c9vcp"
      } ,
      "lang" : "en" ,
      "score" : 35.027836
    } , {
      "mid" : "/m/09dvvy" ,
      "id" : "/en/bob_mcdonnell" ,
      "name" : "Bob McDonnell" ,
      "notable" : {
        "name" : "Politician" ,
        "id" : "/government/politician"
      } ,
      "lang" : "en" ,
      "score" : 34.240498
    } , {
      "mid" : "/m/012gq6" ,
      "id" : "/en/bob_newhart" ,
      "name" : "Bob Newhart" ,
      "notable" : {
        "name" : "Comedian" ,
        "id" : "/m/018gz8"
      } ,
      "lang" : "en" ,
      "score" : 33.925415
    } , {
      "mid" : "/m/047ymw" ,
      "id" : "/en/bob_casey_jr" ,
      "name" : "Bob Casey, Jr." ,
      "notable" : {
        "name" : "U.S. Congressperson" ,
        "id" : "/government/u_s_congressperson"
      } ,
      "lang" : "en" ,
      "score" : 33.472374
    } , {
      "mid" : "/m/019yt" ,
      "id" : "/en/bob_hawke" ,
      "name" : "Bob Hawke" ,
      "notable" : {
        "name" : "Politician" ,
        "id" : "/government/politician"
      } ,
      "lang" : "en" ,
      "score" : 33.388203
    } , {
      "mid" : "/m/0gw5_q" ,
      "id" : "/en/bob_jane" ,
      "name" : "Bob Jane" ,
      "notable" : {
        "name" : "Racing driver" ,
        "id" : "/m/02h6nn_"
      } ,
      "lang" : "en" ,
      "score" : 32.523479
    }
  ] ,
  "cursor" : 20 ,
  "cost" : 29 ,
  "hits" : 177617
}
